"""phase1_match_booking_profile_fields

Revision ID: 69fcdf07d686
Revises: 7a388f780bc9
Create Date: 2026-03-13 11:27:59.200648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69fcdf07d686'
down_revision: Union[str, None] = '7a388f780bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('refund_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('matches', sa.Column('score_home', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('score_away', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('reliability_score', sa.Float(), nullable=False, server_default=sa.text('100.0')))
    op.add_column('user_profiles', sa.Column('total_bookings', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('user_profiles', sa.Column('cancelled_bookings', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('user_profiles', sa.Column('rating', sa.Float(), nullable=False, server_default=sa.text('1200.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'rating')
    op.drop_column('user_profiles', 'cancelled_bookings')
    op.drop_column('user_profiles', 'total_bookings')
    op.drop_column('user_profiles', 'reliability_score')
    op.drop_column('matches', 'score_away')
    op.drop_column('matches', 'score_home')
    op.drop_column('bookings', 'refund_status')
    op.drop_column('bookings', 'cancellation_reason')
    op.drop_column('bookings', 'cancelled_at')
    # ### end Alembic commands ###
